esphome:
  name: power-meter

esp8266:
  board: nodemcuv2

# Enable logging
logger:


# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power-Meter Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:
    

uart:
  - id: main_uart
    rx_pin: D1
    tx_pin: D2
    baud_rate: 9600

modbus:
  - id: mod_bus_pzem1
    send_wait_time: 250ms
    uart_id: main_uart
   
button:
  - platform: template
    name: Reset counter
    id: reset_button

    # Optional variables:
    icon: "mdi:emoticon-outline"
    on_press:
      - pzemac.reset_energy: pzemac_1
      - delay: 500ms
      - pzemac.reset_energy: pzemac_2
      - delay: 500ms
      - pzemac.reset_energy: pzemac_3
      - delay: 500ms

sensor:
  - platform: pzemac
    id: pzemac_1
    current:
      name: "Phase 1 Current"
    voltage:
      name: "Phase 1 Voltage"
    energy:
      name: "Phase 1 Energy"
    power:
      name: "Phase 1 Power"
    frequency:
      name: "Phase 1 Frequency"
    power_factor:
      name: "Phase 1 Power Factor"
    update_interval: 10s
    address: 0x03
    modbus_id: mod_bus_pzem1

  - platform: pzemac
    id: pzemac_2
    current:
      name: "Phase 2 Current"
    voltage:
      name: "Phase 2 Voltage"
    energy:
      name: "Phase 2 Energy"
    power:
      name: "Phase 2 Power"
    frequency:
      name: "Phase 2 Frequency"
    power_factor:
      name: "Phase 2 Power Factor"
    update_interval: 10s
    address: 0x04
    modbus_id: mod_bus_pzem1

  - platform: pzemac
    id: pzemac_3
    current:
      name: "Phase 3 Current"
    voltage:
      name: "Phase 3 Voltage"
    energy:
      name: "Phase 3 Energy"
    power:
      name: "Phase 3 Power"
    frequency:
      name: "Phase 3 Frequency"
    power_factor:
      name: "Phase 3 Power Factor"
    update_interval: 10s
    address: 0x05
    modbus_id: mod_bus_pzem1
  # - platform: pzemac
  #   id: pzemac_4
  #   current:
  #     name: "Stove Current"
  #   voltage:
  #     name: "Stove Voltage"
  #   energy:
  #     name: "Stove Energy"
  #   power:
  #     name: "Stove Power"
  #   #frequency:
  #     #name: "Stove Frequency"
  #   power_factor:
  #     name: "Stove Power Factor"
  #   update_interval: 60s
  #   address: 0x13
  #   modbus_id: mod_bus_pzem1


# wifi sensor
  - platform: uptime
    name: Power Meter Uptime
  - platform: wifi_signal
    name: Power Meter WiFi Signal
    update_interval: 60s
# system action
switch:
  - platform: restart
    name: "Power Meter Restart"

time:
  - platform: homeassistant
    id: homeassistant_time
 
text_sensor:
  - platform: version
    name: Power Meter ESPHome Version
  - platform: wifi_info
    ip_address:
      name: Power Meter IP
    ssid:
      name: Power Meter SSID
    bssid:
      name: Power Meter BSSID
# System status configuration
binary_sensor:
  - platform: status
    name: "Power Meter Status"
